# --- !Ups

create table "USER" (
"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
"USERNAME" VARCHAR NOT NULL,
"PASSWORD" VARCHAR NOT NULL
);

insert into "USER" ("USERNAME","PASSWORD","ID") VALUES ('diego@diego2.it','welcome2',123);
insert into "USER" ("USERNAME","PASSWORD") VALUES ('diego@diego.it','welcome1');
insert into "USER" ("USERNAME","PASSWORD","ID") VALUES ('diego@diego3.it','welcome2',1);

# --- !Downs

drop table "USER";

