# --- !Ups

create table "user" (
"password" VARCHAR, 
"username" VARCHAR NOT NULL,
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
);

# --- !Downs

drop table "user";

